### ISSUE TITLE
I2C protocol

### ISSUE THREAD

**Issue by SimaWB** [igor-morawski/HTPA32x32d#2]
Hi Igor;
This is not issue, so sorry for writing here :(
Do you have Python library for I2C communication to Heimann HTPA sensor. Especially I've HTPA 8x8 module.
Best wishes...

**Comment by igor-morawski** [comment]
Hello, 

I am using a UDP communication module that comes with the starter kit so I have no experience with I2C with this sensor. It seems that https://github.com/loganwilliams/thermografree is what you're looking for.

**Comment by SimaWB** [comment]
Thanks for your replay Igor.
I've the kit too. But I'm doing research for i2c. Thanks again...
