### ISSUE TITLE
Data Meaning

### ISSUE THREAD

**Issue by Raj9417** [igor-morawski/HTPA32x32d#4]
HTPA32x32d
2987 2992 2984 2990 2994 2977 2983 3006 3002 2990 2971 2982 2977 2987 2992 3009 2995 2989 3005 2992 2988 2986 2982 2978 2951 2981 2959 2963 2961 2950 2956 2941 2969 2971 3000 2976 2972 2986 2971 2978 2977 2979 2995 2993 2984 3010 2997 3032 3025 3024 3012 2998 2980 2985 2978 2967 2970 2976 2964 2979 2967 2971 2965 2950 2992 2979 2976 2992 3001 2993 2989 2988 2997 2973 2981 2976 2989 3011 3029 3037 3035 3031 3021 2992 3005 2996 2984 2975 2968 2980 2981 2964 2957 2943 2974 2954 2993 2986 2968 2998 2982 3005 2987 2998 2999 2988 2995 2999 3001 3033 3060 3071 3061 3064 3057 3028 3004 2995 2990 2983 2972 2976 2960 2978 2960 2954 2949 2953 2983 2990 2986 3002 2989 3008 2996 3014 2996 2998 3006 2999 3010 3051 3057 3059 3060 3072 3071 3059 3027 3015 2989 2992 2967 2974 2980 2985 2957 2960 2963 2962 2971 2998 3000 2994 2993 2999 2985 2993 2987 2997 2998 3023 3056 3065 3068 3048 3045 3073 3066 3069 3052 3024 3007 3001 2985 2978 2981 2973 2972 2977 2968 2975 2998 2990 2981 3000 3002 2989 3013 2989 2988 3010 3016 3030 3026 3035 3048 3033 3045 3055 3068 3040 3035 3023 3019 2993 3010 3000 2983 2975 2961 2980 2974 2961 2992 3002 2995 2984 2989 2990 2990 2996 3001 3019 3023 2985 2998 2993 3034 3064 3058 3053 3079 3051 3045 3033 3025 3004 2995 3002 2999 2963 2993 2970 2980 2961 2987 2989 3002 2990 3004 2973 2988 3036 3033 3053 3008 3000 2989 3005 3044 3062 3044 3064 3078 3063 3077 3045 3036 3005 2998 3008 2989 2975 2963 2967 2960 2982 2994 2984 2990 2999 2994 2989 3008 2994 2999 3030 2997 3005 2985 3038 3076 3078 3075 3062 3046 3058 3053 3046 3045 3029 3016 3002 2978 2974 2984 2978 2971 2967 2979 2979 2983 3004 2995 2999 3011 3010 3029 3030 2994 3002 3032 3066 3069 3068 3064 3063 3042 3047 3036 3051 3060 3025 3015 3013 2996 2964 2963 2963 2980 2957 3001 3003 2982 3003 2990 2980 3005 3028 3029 3028 3038 3059 3069 3075 3065 3067 3040 3048 3052 3047 3054 3058 3063 3037 3045 2997 2990 2983 2976 2970 2968 2968 2970 2988 2981 2984 2993 2990 2997 3030 3059 3060 3071 3081 3070 3068 3059 3050 3058 3045 3038 3045 3064 3059 3044 3032 3004 2995 2987 2978 2979 2979 2968 2975 2988 2993 3006 2987 2991 2994 2999 3053 3050 3053 3079 3058 3063 3076 3067 3064 3056 3055 3036 3053 3058 3066 3063 3026 3007 2983 2993 2965 2971 2982 2999 2987 2984 3002 2981 2997 3004 2998 3024 3072 3068 3054 3049 3054 3058 3061 3070 3057 3063 3070 3050 3037 3066 3062 3063 3029 3016 2986 2970 2971 2977 2970 2981 2972 2980 3002 2999 2997 2993 3005 3041 3079 3059 3069 3066 3065 3058 3057 3046 3060 3061 3060 3060 3045 3071 3049 3057 3006 2991 2987 2980 2979 2983 2969 2978 2967 2999 2994 2967 2991 2991 2999 3042 3062 3064 3079 3075 3046 3064 3045 3040 3064 3051 3074 3073 3046 3045 3024 3008 3012 2986 2962 2971 2976 2967 2983 2967 3001 3003 2994 2976 2996 3008 3003 3025 3067 3083 3072 3063 3067 3061 3064 3056 3060 3069 3065 3054 3050 3049 3031 3026 3030 2997 2980 2983 2988 3004 2972 2969 2980 2999 2989 2998 2991 2995 2995 3031 3056 3063 3067 3063 3065 3077 3048 3056 3071 3048 3048 3065 3068 3072 3057 3053 3024 2990 2969 2977 2983 2970 2981 2965 2964 3008 2992 2994 2982 2994 2982 3030 3043 3054 3064 3069 3065 3060 3066 3060 3064 3055 3049 3052 3053 3048 3048 3024 2975 2983 2979 2973 2969 2969 2974 2958 2950 2985 2982 3003 2991 2995 2981 3024 3049 3039 3069 3062 3056 3058 3058 3056 3069 3053 3056 3053 3038 3048 3049 2996 2979 2968 2975 2976 2967 2975 2957 2989 2993 3004 2981 2990 2992 2993 2986 2995 3022 3074 3066 3072 3083 3053 3073 3071 3059 3061 3049 3064 3042 3066 3025 2981 2958 2977 2958 2987 2979 2989 2988 2986 2967 3007 2984 2992 2993 2978 2981 2994 3000 3027 3080 3054 3076 3060 3050 3054 3076 3054 3070 3044 3057 3047 2998 2989 2977 2974 2980 2980 2979 2979 2960 2961 2953 2991 2989 2992 2987 2985 2993 2994 2997 2992 3052 3064 3079 3080 3070 3067 3059 3053 3064 3065 3049 3004 2975 2990 2985 2974 2976 2983 2967 2975 2965 2965 2967 3006 2989 2987 2987 2992 3007 3011 3008 3026 3072 3073 3064 3055 3064 3068 3073 3067 3059 3034 3006 2991 2983 2973 2999 2964 2979 2978 2973 2970 2965 2968 2970 3007 3012 2981 3026 3012 3001 3001 3003 3052 3059 3072 3088 3057 3084 3024 3036 3022 3005 2982 2992 3008 3001 2989 2977 2978 2989 2973 2987 2973 2982 2968 2975 2997 3008 3012 3020 3012 3000 3008 3013 3038 3050 3031 3022 3012 3025 2996 3015 3014 3024 3014 3001 3011 2996 2992 2975 2974 2986 2979 2968 2961 2970 2970 2995 3014 3015 3004 3005 3010 3019 3033 3029 3023 3019 3035 3027 3023 3029 3010 3018 3023 3022 3000 2997 3003 2977 2970 2971 2996 3006 3016 2984 2985 2973 2957 2964 3001 3013 3009 3020 3013 2998 3019 3025 3012 3035 3015 3010 3027 3009 3011 3020 3026 3028 3017 3000 2976 2984 2980 3000 2999 2996 3007 3004 2974 3002 2954 2982 3025 3028 2999 3016 3012 3021 2990 3009 3030 3008 3003 3008 2984 3022 3006 3006 2994 2997 2982 2991 2996 2985 3000 3018 3008 3001 2997 3007 3002 2999 2983 2973 3010 2998 3010 3002 2997 3014 3007 3009 3006 3010 2979 2971 2983 3001 2980 3005 2995 3003 3001 3000 2996 2993 3005 3005 2991 3003 2998 3019 2979 2979 2994 2972 2998 3013 3011 2984 3014 2998 2984 2999 2996 3002 2987 2983 3000 3005 2998 3012 3015 2995 2998 2998 2984 2979 2985 2986 2995 2996 3002 2995 2978 2993 2999 2962 -31136 -31383 -31266 -31443 -31197 -31045 -31236 -30869 -31177 -31380 -31306 -30892 -31586 -30789 -31282 -31060 -31139 -31352 -30867 -30643 -31081 -30740 -31061 -31311 -31271 -31066 -31416 -31218 -31183 -31249 -30870 -31421 -31442 -31153 -31176 -30728 -31326 -31305 -31006 -31159 -30828 -30726 -30950 -31250 -30741 -31278 -30904 -30740 -31146 -31326 -31581 -31494 -30676 -31028 -31167 -31220 -31341 -31280 -31236 -31187 -31115 -31290 -31495 -31193 -31482 -31049 -31073 -30891 -31281 -30933 -31067 -31083 -30989 -31053 -31339 -31106 -30876 -31231 -30995 -30939 -31223 -31313 -31046 -31327 -31226 -31096 -31169 -31319 -31371 -31281 -30606 -31596 -31119 -31438 -31126 -31225 -31014 -31323 -30654 -31314 -30911 -31557 -31081 -30626 -30967 -31202 -31192 -31087 -31465 -31193 -31047 -31054 -31416 -31238 -31411 -31133 -31282 -31244 -31555 -31457 -31377 -31405 -31066 -31401 -31528 -31559 -31068 -31711 -31628 -31301 -31481 -31209 -31088 -31306 -31239 -31179 -31263 -31399 -31451 -31403 -30991 -31524 -31107 -30874 -31485 -31135 -31095 -31123 -31179 -31583 -31225 -31747 -31286 -31687 -31373 -31559 -31059 -31271 -31251 -31409 -30907 -31560 -31062 -31176 -31219 -31273 -31527 -30979 -30853 -31124 -31026 -30804 -31278 -31099 -30979 -31060 -30850 -31087 -31276 -30682 -31123 -30826 -31375 -31205 -31359 -31560 -31136 -30990 -31558 -31257 -31251 -31081 -30943 -30868 -31129 -31433 -31256 -31275 -30809 -31084 -30841 -31195 -31253 -31194 -30956 -31090 -30881 -30721 -31026 -30758 -31076 -31449 -31021 -30997 -31092 -31155 -31140 -31293 -30823 -31445 -30963 -31276 -30999 -31381 -31725 -31272 -31132 -31355 -31436 -30998 -31574 -30913 -31117 -31089 -30956 -30887 -31139 -31333 -31165 -31524 -31176 -31231 -31094 -30949 -30852 -31449 -31305 -31793 -31170 -31322 -31336 -31247 -31291 -31354 -31446 -31541 -26034 3069 -29797 -30941 -29795 -30942 -29797 -30941 -29799 -30938 t: 3.21

Above is the data receive from the sensor. May I Know how to get the ambient temperature, or which of the above data is the ambient temperature. Thank You.

**Comment by igor-morawski** [comment]
First 32\*32=1024 elements are temperature values captured by the sensor in 0.01⁰C (e.g., 2987 means 2987*0.01⁰C=29.87⁰C). The last element t: 3.21 will be the time in seconds after starting the program at which the data frame was captured. The rest (in between) are to be ignored.

The reason why the data is saved in this format is because this is exactly the format originally used by the producer in their software. In this way, files saved by Heimann's software can be still processed by functions in this module.

**Comment by Raj9417** [comment]
@igor-morawski Thank You for the answer. Sorry to ask again, may I know how to get ambient temperature from this data? Thank You
